export {default as Hero} from './hero/Hero'
export {default as Treatments} from './treatments/Treatments'
export {default as About} from './about/About'
export {default as Cta} from './cta/Cta'
export {default as Footer} from './footer/Footer'